language: java

env:
  global:
  - SMALLD_VERSION="$(git describe --dirty --tags)-SNAPSHOT"
  - MAVEN_OPTS="-Drevision=$SMALLD_VERSION -Dproperty=revision -DnewVersion=$SMALLD_VERSION -DgenerateBackupPoms=false"

addons:
  sonarcloud:
    organization: "ianagbip1oti-github"

before_install:
- 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then bash ./etc/extract_secrets.sh; fi'

stages:
- build
- name: snapshot
  if: branch = master AND NOT type = pull_request
- name: release
  if: tag =~ ^\d+\.\d+\.\d+$
  
jobs:
  include:
    - stage: build
      jdk: oraclejdk8
      script: mvn -B verify
    - jdk: oraclejdk9
      script: mvn -B verify
    - jdk: openjdk8
      script: mvn -B verify
    - stage: snapshot
      jdk: openjdk8
      script: mvn -s etc/settings.xml -B versions:set-property deploy -P release
    - stage: release
      jdk: openjdk8
      env:
        - SMALLD_VERSION=$(git describe --dirty --tags)
        - MAVEN_OPTS="-Drevision=$SMALLD_VERSION -Dproperty=revision -DnewVersion=$SMALLD_VERSION -DgenerateBackupPoms=false"
      script: mvn -s etc/settings.xml -B versions:set-property deploy -P release

